
CFLAGS= -g --std=gnu11 -O0 -fno-inline -Wall
COMPILE_OPTIONS=-DDEBUG

all: prepwork euler011

prepwork:
	@if test -d ../bin; then echo BinOk >& /dev/null ; else mkdir -p ../bin; fi
	@cp grid.txt ../bin

euler011: euler011.c
	clang $(CFLAGS) $(COMPILE_OPTIONS) -o euler011 euler011.c 
	mv euler011 ../bin


clean:
	rm -rf *.dSYM
	rm -f *.o
	rm -f ../bin/euler011

remake:
	make clean
	make all
