
EULERLIBDIR=$(shell sh -c 'cd ../lib; pwd')
EULERINCDIR=$(shell sh -c 'cd ../euler; pwd')

CPPFLAGS  = -O3 -Wall -Werror -fPIC
# CPPFLAGS  = -g -O0 -Wall -Werror -fPIC
CPPFLAGS += -std=c++0x -stdlib=libc++
LDFLAGS   = -stdlib=libc++
LDLIBS    = -L$(EULERLIBDIR) -leuler
INCLUDE   = -I$(EULERINCDIR)
CXX = c++

all: euler013 \
	mover

mover:
	mv euler013 ../bin

clean:
	rm -rf *.dSYM/
	rm -f *.o
	rm -f ../bin/euler013
