
CFLAGS= -g --std=gnu11 -O0 -fno-inline -Wall
COMPILE_OPTIONS=-DDEBUG

all: prepwork euler024

prepwork:
	@if test -d ../bin; then echo BinOk >& /dev/null ; else mkdir -p ../bin; fi

euler024: euler024.c
	mpicc $(CFLAGS) $(COMPILE_OPTIONS) -o euler024 euler024.c 
	mv euler024 ../bin


clean:
	rm -rf *.dSYM
	rm -f *.o
	rm -f ../bin/euler024

remake:
	make clean
	make all
