
all:
	make -C problem003
	make -C problem010
	make -C problem014
	make -C problem092

clean:
	make clean -C problem003
	make clean -C problem010
	make clean -C problem014
	make clean -C problem092

remake:
	make clean
	make all
