
all:
	make -C euler 
	make -C problem001
	make -C problem002
	make -C problem003
	make -C problem004
	make -C problem005
	make -C problem014

clean:
	make clean -C euler
	make clean -C problem001
	make clean -C problem002
	make clean -C problem003
	make clean -C problem004
	make clean -C problem005
	make clean -C problem014

remake:
	make clean
	make all
