
all:
	make -C euler 
	make -C problem001
	make -C problem002
	make -C problem003
	make -C problem004
	make -C problem005
	make -C problem008
	make -C problem009
	make -C problem010
	make -C problem012
	make -C problem013
	make -C problem014
	make -C problem015
	make -C problem017
	make -C problem018
	make -C problem022

clean:
	make clean -C euler
	make clean -C problem001
	make clean -C problem002
	make clean -C problem003
	make clean -C problem004
	make clean -C problem005
	make clean -C problem008
	make clean -C problem009
	make clean -C problem010
	make clean -C problem012
	make clean -C problem013
	make clean -C problem014
	make clean -C problem015
	make clean -C problem017
	make clean -C problem018
	make clean -C problem022

remake:
	make clean
	make all
