
EULERLIBDIR=$(shell sh -c 'cd ../lib; pwd')
EULERINCDIR=$(shell sh -c 'cd ../euler; pwd')

CPPFLAGS  = -O3 -Wall -Werror -fPIC
CPPFLAGS += -std=c++0x -stdlib=libc++
LDFLAGS   = -stdlib=libc++
LDLIBS    = -L$(EULERLIBDIR) -leuler
INCLUDE   = -I$(EULERINCDIR)
CXX = c++

all: euler005 euler005_tmplt \
	mover

mover:
	mv euler005       ../bin
	mv euler005_tmplt ../bin

clean:
	rm -rf *.dSYM/
	rm -f *.o
	rm -f ../bin/euler005
	rm -f ../bin/euler005_tmplt


