
EULERLIBDIR=$(shell sh -c 'cd ../lib; pwd')
EULERINCDIR=$(shell sh -c 'cd ../euler; pwd')

CPPFLAGS  = -O3 -Wall -Werror -fPIC
CPPFLAGS += -std=c++11 -stdlib=libc++
LDFLAGS   = -stdlib=libc++
LDLIBS    = -L$(EULERLIBDIR) -leuler
INCLUDE   = -I$(EULERINCDIR)
CXX = c++

all: euler001a euler001b euler001c mover

mover:
	mv euler001a ../bin
	mv euler001b ../bin
	mv euler001c ../bin

clean:
	rm -rf *.dSYM/
	rm -f *.o
	rm -f ../bin/euler001a
	rm -f ../bin/euler001b
	rm -f ../bin/euler001c


